# Generated by Django 4.1 on 2022-11-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_alter_preguntas_pregunta_alter_preguntas_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntas',
            name='Pregunta',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='Titulo',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='idRespuesta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
