# Generated by Django 4.1 on 2022-11-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0003_alter_preguntas_pregunta_alter_preguntas_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=12, unique=True, verbose_name=''),
        ),
    ]
